# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2235632d2a56d63a851f352bc86d948644c79a9a74e46e33c46227945f384981dca37b01fc7ffaa6fb265ea3227d66b01fc96fcd637ad552355fd90ab6f6a375

test:
  secret_key_base: 8a4195a1ec246f9cb29edb69f07a083f70ebebc58035a69455ddf8702b84de6ddd8df8883545e95a312d682aea3f288c65c5fbba2328d02786052624e3a19643

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
